### ISSUE TITLE
 sebastian/resource-operations is abandoned

### ISSUE THREAD

**Issue by jbouwh** [roy-bongers/certbot-transip-dns-01-validator#140]
When updating the software using composer the following warning is displayed:
`Package sebastian/resource-operations is abandoned, you should avoid using it. No replacement was suggested.`

This package should not be used anymore.

**Comment by roy-bongers** [comment]
The package generating the warning is a dependency from phpunit. There is an (closed) issue which mentions this: https://github.com/sebastianbergmann/phpunit/issues/4714#issuecomment-864419127 . I don't think there is much more I can do then wait for phpunit 10 to be released. This will also mean that PHP 7.4 support will be have to be dropped because phpunit 10 will only support PHP >= 8.0

**Comment by jbouwh** [comment]
Debian buster is still on php 7.3

**Comment by roy-bongers** [comment]
Yes, I'm fully aware of that. I'm planning on creating a 3.x version which will drop php 7 support and will include all the good stuff from PHP 8. Version 2.0 will then be maintained until PHP 7.4 is end of life (november 28th 2022).

**Comment by roy-bongers** [comment]
The package sebastian/resource-operations is not marked as abandoned anymore which fixes this issue.
